### ISSUE TITLE
Fit does not work with built-in Sherpa models

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#746]
I'm using a grating spectrum downloaded from http://tgcat.mit.edu (I see the same behaviour for all datasets I tried, but to reproduce my code below exactly, download OBSID 7437).

First, I load the data (here, I take just one spectrum in the PHA II file, but I have the same problem when I try other spectra or several at the same time), and ignore everything except for a specific emission line. This line, I want to fit with a Gaussian, so I set one up and freeze position and FWHM. Then, I set some grouping and turn to cstat (I see the same problem with other statistics I tried, but cstat is the most appropriate for this data):
```
from sherpa.astro import ui

%matplotlib inline

path = '/melkor/d1/guenther/downdata/Chandra/TWHya/tgcat/obs_7437_tgid_4057/'
ui.load_data(path + 'pha2.gz')
ui.load_arf(10, path+"meg_1.arf.gz")
ui.load_rmf(10, path+"meg_1.rmf.gz")

ui.set_analysis('wave')
ui.ignore(None, 21.4)
ui.ignore(21.7, None)
ui.notice(21.4, 21.7)

line = ui.gauss1d(name='line')

line.fwhm.val = 0.00001
line.fwhm.frozen = True
line.pos = 21.6
line.pos.frozen = True

ui.set_source(10, line)
ui.group_width(10, 2)
ui.set_stat("cstat")
ui.fit(10)
```

The fit does not change the amplitude of the line, in fact it stops at function evaluation 2:
```
Dataset               = 10
Method                = levmar
Statistic             = cstat
Initial fit statistic = 1140.66
Final fit statistic   = 1140.66 at function evaluation 2
Data points           = 62
Degrees of freedom    = 61
Probability [Q-value] = 9.01448e-199
Reduced statistic     = 18.6993
Change in statistic   = 0
   line.ampl      1            +/- 0   
```
Yet, it's clearly a bad fit:
![image](https://user-images.githubusercontent.com/498688/75265106-69e15800-57be-11ea-8ac2-fa48558c50dd.png)

If I change `line.ampl` by hand, and re-run the fit, it reports **the same value for the fit statistic**, although a plot shows that the line now fits better and thus the fit statistic should have changed:
```
line.ampl = 10
ui.fit(10)
```
gives me:
```
WARNING: data set 10 has associated backgrounds, but they have not been subtracted, nor have background models been set
Dataset               = 10
Method                = levmar
Statistic             = cstat
Initial fit statistic = 1140.66
Final fit statistic   = 1140.66 at function evaluation 2
Data points           = 62
Degrees of freedom    = 61
Probability [Q-value] = 9.01448e-199
Reduced statistic     = 18.6993
Change in statistic   = 0
   line.ampl      10           +/- 0  
```

Curiously, if I get the fit statistic and display it, I see very different numbers:
```
statinfo = ui.get_stat_info()[0]
print(statinfo.statval)
```
gives 8.209025337224736. Why is this number different from the reduced statistic that `ui.fit()` reports? The number I see in statinfo also changes, when I change the model. Why does the fit not optimize that number, and instead prints out some constant?

If, instead of the buildin Sherpa `gauss1d` I use XSPEC's `xsgaussian` the fit works, so this is likely a problem with the Sherpa models and not with my input data.

**Comment by dtnguyen2** [comment]
So LevMar method only did 2 function evaluations, not enough info to go on,  so I made the following changes to the script:
```
ui.set_method('neldermead')
ui.fit(10, outfile='out.txt')
```
The optional argument, ```outfile='out.txt'``` to the fit command is to see what function values were  tried.  As one can see, the _out.txt_ file
```
(sherpa) [dtn@devel12 hans]$ wc out.txt 
 1014  3043 39666 out.txt
```
the maximum number of function evaluations were tried.  Unfortunately, while the third column which is the ```line.ampl``` free parameters were varied but the second column which is the stat did not:
```
(sherpa) [dtn@devel12 hans]$ head -10 out.txt 
# nfev statistic line.ampl
0.000000e+00 1.151747e+03 1.000000e+00
1.000000e+00 1.151747e+03 2.200000e+00
2.000000e+00 1.151747e+03 -2.000000e-01
3.000000e+00 1.151747e+03 1.600000e+00
4.000000e+00 1.151747e+03 1.600000e+00
5.000000e+00 1.151747e+03 4.000000e-01
6.000000e+00 1.151747e+03 1.300000e+00
7.000000e+00 1.151747e+03 1.300000e+00
8.000000e+00 1.151747e+03 7.000000e-01
...
```

**Comment by dtnguyen2** [comment]
BTW, the  stat did not changed for basically min (-1.36e+38) and max (2.72e+38) values of floating point number for the ```line.ampl``` free parameter.
```
(sherpa) [dtn@devel12 hans]$ grep +38 out.txt 
2.520000e+02 1.151747e+03 -1.361129e+38
2.530000e+02 1.151747e+03 -2.722259e+38
2.540000e+02 1.151747e+03 -1.361129e+38
2.550000e+02 1.151747e+03 2.722258e+38
```
Tough to minimize the statistic under this condition.

**Comment by hamogu** [comment]
@dtnguyen2 : Yes, but why did the stat not change? I did not notice that changing the line.ampl does not change the stat in the output of fit, but it *does* change the `ui.get_stat_info()[0],statval`. So, I suspect that the statval that the fit sees is wrong? If you make `plot_fit` with different values of `line.ampl` you also see that the model fits more or less (reasonable values to plot are  line.ampl  between 0.01 and 10 or so). So the stat *should* change, but it does not.

**Comment by dtnguyen2** [comment]
@DougBurke made an interesting observation, which was sent to _sherpadev_ so I don't think you saw it.  He noticed that using CIAO4.10 release (March 30, 2018), he was able to get sherpa to return a decent fit.   Using his discovery, I noticed that release 4.10.0 (May 2, 2018) was still giving a decent fit, but using release 4.10.1 (October 16, 2018) the fit started to diverge from the previous release (4.10.0 on May 2, 2018).

```
(sherpa) [dtn@devel12 hans]$ diff levmar-4.10.1.txt levmar-4.10.0.txt
11c11
<  VERSION: {'version': '4.10.1+0.g34fc4556.dirty', 'full': '34fc455622d40e463c734ec919a15e8f6ce9367c.dirty'}
---
>  VERSION: {'version': '4.10.0+0.g654fe737.dirty', 'full': '654fe737f4ffc3d73083baa2adcf5b2daf5ec664.dirty'}
24,25c24,25
< Initial fit statistic = 1151.75
< Final fit statistic   = 1151.75 at function evaluation 2
---
> Initial fit statistic = 43.2211
> Final fit statistic   = 2.57681 at function evaluation 14
28,31c28,31
< Probability [Q-value] = 2.58371e-222
< Reduced statistic     = 37.1531
< Change in statistic   = 0
<    line.ampl      1           
---
> Probability [Q-value] = 1
> Reduced statistic     = 0.0831231
> Change in statistic   = 40.6443
>    line.ampl      19.7173     
33,35c33,35
< fit before : 1151.7471638402303
<     after  : 1151.7471638402303
<     delta  : 0.0
---
> fit before : 43.2211459879258
>     after  : 2.5768146402448835
>     delta  : 40.64433134768092
38c38
< Stat after : 43.2211459879258
---
> Stat after : 2.5768146402448835
40c40
<            : 43.2211459879258
---
>            : 2.5768146402448835
```

**Comment by hamogu** [comment]
@dtnguyen2 : That is correct, I'm not on sherpadev. I'm glad to see though that it's not just a user error, but something that did work in the past.

**Comment by dtnguyen2** [comment]
Using _git bisect_ shows that PR #444  is the culprit:

```
Dataset               = 10
Method                = levmar
Statistic             = cstat
Initial fit statistic = 1151.75
Final fit statistic   = 1151.75 at function evaluation 2
Data points           = 32
Degrees of freedom    = 31
Probability [Q-value] = 2.58371e-222
Reduced statistic     = 37.1531
Change in statistic   = 0
   line.ampl      1           
a0999bb5af320266231528b7756f055806b56e02 is the first bad commit
commit a0999bb5af320266231528b7756f055806b56e02
Author: Dan Nguyen <dnguyen@cfa.harvard.edu>
Date:   Wed Apr 18 13:07:26 2018 -0400

    Use cached models when possible

:040000 040000 4cc05fff2bc5fa0be546c4b9387a0add505fbfba 2544fc4863781122c743d95dc803789aea6d9b3b M	sherpa
bisect run success
```

**Comment by dtnguyen2** [comment]
PR #759 should fix this issue

**Comment by hamogu** [comment]
Great! Thanks everyone for the fast turn-around!

**Comment by DougBurke** [comment]
A workaround for this is the following patch (which can be used without waiting for an update). It has been lightly tested, but I believe has the important part of #759 in it:

```python
from sherpa.astro.instrument import RSPModelPHA, apply_areascal

# Apply the fix for #746
#
def patched_calc(self, p, x, xhi=None, *args, **kwargs):

    src = self.model.calc(p, self.xlo, self.xhi)
    src = self.arf.apply_arf(src, *self.arfargs)
    src = self.rmf.apply_rmf(src, *self.rmfargs)
    return apply_areascal(src, self.pha,
                          "RMF: {}".format(self.rmf.name))

RSPModelPHA.calc = patched_calc
```

**Comment by hamogu** [comment]
I'm just right now trying to install the current master from source. (Would be good if I manage anyway.) If that fails, I'll try out this patch. Thanks!

**Comment by DougBurke** [comment]
For my own notes: I had hoped we could simplify the work around by just turning off the model cache, but setting

    line.cache = 0

does not fix the issue, so you have to use something like `patched_calc` from above.
